### ISSUE TITLE
Add Support for s390x and ppc64le

### ISSUE THREAD

**Issue by james-crowley** [gotestyourself/gotestsum#268]
@dnephin I saw a couple PRs and additions for various architectures like #181. Would you be open to adding `s390x` and `ppc64le`?

`s390x` refers to the mainframe architecture on Linux or common referred to Linux on Z. While `ppc64le` refers to the Power architecture. Both architectures are made by IBM, even though some of it is open source. 

From my experience both `s390x` and `ppc64le` both have great support in GO and usually cross compile without issue. 

I believe the `.goreleaser.yml` would need to be update to look something like:

```yaml

project_name: gotestsum

release:
  github:
    owner: gotestyourself
    name: gotestsum

builds:
  - binary: gotestsum
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - s390x
      - ppc64le
    env: [CGO_ENABLED=0]
    ldflags: ["-s -w -X gotest.tools/gotestsum/cmd.version={{.Version}}"]

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

``` 

@dnephin If you are open to support those architecture, I can submit a PR for you if you would like!
